# Generated by Django 3.1.7 on 2021-03-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=100)),
            ],
        ),
    ]
