# Generated by Django 3.1.7 on 2021-03-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winners', '0003_auto_20210327_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='male', max_length=100),
        ),
    ]
