# Generated by Django 3.1.7 on 2021-03-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winners', '0004_auto_20210328_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='winner',
            name='category',
            field=models.CharField(default='Match 1', max_length=255),
        ),
    ]
