# Generated by Django 3.1.7 on 2021-03-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winners', '0005_auto_20210328_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='full_name',
            new_name='name',
        ),
    ]
