# Generated by Django 3.1.7 on 2021-03-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winners', '0006_auto_20210328_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='category',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Match 1', max_length=255),
        ),
    ]
