# Generated by Django 3.1.7 on 2021-03-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winners', '0008_auto_20210328_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='category',
            field=models.CharField(choices=[('Match 1', 'Match 1'), ('Match 2', 'Match 2'), ('match', 'match')], default='Match 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='winner',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
