# Generated by Django 3.1.7 on 2021-04-12 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winners', '0012_auto_20210409_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='categories',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='winners.category'),
        ),
    ]
