# Generated by Django 3.1.7 on 2021-03-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210309_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match1',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
