# Generated by Django 3.1.7 on 2021-03-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210309_2027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match1',
            new_name='Match_1_Register',
        ),
    ]
