# Generated by Django 3.1.7 on 2021-03-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210311_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_1_register',
            name='image',
            field=models.URLField(),
        ),
    ]
