# Generated by Django 3.1.7 on 2021-03-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210311_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_1_register',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=100),
        ),
    ]
