# Generated by Django 3.1.7 on 2021-03-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210312_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_1_register',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Match1'),
        ),
    ]
