# Generated by Django 3.1.7 on 2021-03-13 09:48

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210312_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_1_register',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Match1', validators=[main.validators.validate_file_extension]),
        ),
    ]
